### ISSUE TITLE
Mehrere Jahre in einer Instanz unterstützen

### ISSUE THREAD

**Issue by christian-heusel** [FachschaftMathPhys/Finance-Visualizer#3]
Der Visualizer sollte auch die Möglichkeit bieten, zwischen mehreren Jahren umzuschalten.

**Comment by TuringTux** [comment]
Ich nehme an, idealerweise ohne Page Reload? Dann wäre es vermutlich ganz schön, das Jahr als Fragment in die URL zu packen (`https://mathphys.info/finanzen/#2019`).

Aufs UI würde ich dann glaube ich einen Dropdown packen (vielleicht in einen neuen Tab? Das wäre zumindest einfach), über den man das Jahr auswählen kann, das dann im Fragment aktualisiert wird.

Datentechnisch bin ich mir nicht sicher, aber vielleicht so etwas mit Unterordnern für jedes Jahr, in denen sich dann je eine `einnahmen.js` und eine `ausgaben.js` befinden (bzw. halt eine `einnahmen.irgendwas`, je nach bevorzugtem Format)?

**Comment by TuringTux** [comment]
Der Dropdown passt eigentlich ganz schön in die Unterüberschrift (da, wo jetzt auch aktuell schon das Jahr steht).
Ich habe das mal entworfen, hätte auch schon einen Quick'n'Dirty-Hack, der für das aktuell Setup bei MathPhysInfo funktionieren sollte: https://github.com/TuringTux/Finance-Visualizer/tree/quick-and-dirty

Der Dropdown ändert einfach die aktuell offene Page zu der Instanz des ausgewählten Jahrs. Nicht sehr schön, aber geht.

**Comment by TuringTux** [comment]
Okay, es wird: https://github.com/TuringTux/Finance-Visualizer/tree/year-switcher

Jetzt muss ich noch die Daten von 2017 und 2018 ins neue Format bringen (ich habe damit schon mal angefangen, aber es gestaltet sich etwas schwieriger als erhofft) und dann `js/display.js` aufräumen (da scheinen aktuell noch Bugs drin zu sein).

Edit: Außerdem hängt auch der Text in "Allgemein" vom Jahr ab (und das dort verlinkte PDF), dafür müsste ich mir auch noch was einfallen lassen.

Schreibt mir gerne eine Nachricht, falls ihr Fragen oder Anregungen habt :smiley:
