### ISSUE TITLE
Clear file structure

### ISSUE THREAD

**Issue by christian-heusel** [FachschaftMathPhys/Finance-Visualizer#5]
- `einnahmen.js` & `ausgaben.js` sollten jeweils nur ein jeweils benannten Array mit den Einnahmen und Ausgaben enthalten
- der redundante Code sollte entfernt werden
- der Code für die Funktionalität sollte in ein extra JS File

**Comment by ThorstenBuss** [comment]
Dieses Issue ist im 2019-Branch gelöst.
